# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
FROM openjdk:8
maintainer JavaPathshala.com
expose 8301:8301
add /target/add-service.jar add-service.jar
entrypoint ["java","-jar","opt/add-service.jar"]
