spring:
    application:
        name: Eureka-Service

server:
    port: 8301

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
       waitTimeInMsWhenSyncEmpty: 0 
